# Generated by Django 3.2.12 on 2022-05-09 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flexpage',
            options={'verbose_name': 'Flex Page2', 'verbose_name_plural': 'Flex Pages2'},
        ),
    ]
