# Generated by Django 3.2.12 on 2022-05-09 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('flex', '0003_auto_20220509_1225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flexpage',
            options={'verbose_name': 'Flex Page2', 'verbose_name_plural': 'Flex Pages2'},
        ),
        migrations.DeleteModel(
            name='FlexiPage',
        ),
    ]
