# Generated by Django 3.2.12 on 2022-05-09 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0004_auto_20220509_1227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flexpage',
            options={'verbose_name': 'Flex Page', 'verbose_name_plural': 'Flex Pages'},
        ),
    ]
