# Generated by Django 3.2.12 on 2022-05-09 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0005_alter_flexpage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flexpage',
            options={'verbose_name': 'Flexi Page', 'verbose_name_plural': 'Flex Pages'},
        ),
    ]
